name: CI

on:
  push:
    branches:
      - main
    paths:
      - apis/**
  workflow_dispatch: {}

env:
  DOCKER_USR: ${{ secrets.DOCKERHUB_USERNAME }}
  PACKAGE_NAME: acmeco/configuration-acme-api

jobs:
  configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Set tag
        run: echo "::set-output name=VERSION_TAG::$(git describe --dirty --always --tags | sed 's/-/./2' | sed 's/-/./2' )"
        id: tagger
      - name: Login to Upbound Marketplace
        uses: docker/login-action@v1
        if: env.DOCKER_USR != ''
        with:
          registry: xpkg.upbound.io
          username: ${{ secrets.XPKG_ACCESS_ID }}
          password: ${{ secrets.XPKG_ACCESS_TOKEN }}
      - name: Build
        uses: crossplane-contrib/xpkg-action@v0.2.0
        with:
          channel: stable
          version: current
          command: build configuration -f ${{ github.workspace }}/apis --name package.xpkg
      - name: Push to Upbound Marketplace
        uses: crossplane-contrib/xpkg-action@v0.2.0
        with:
          command: push configuration -f apis/package.xpkg xpkg.upbound.io/${PACKAGE_NAME}:${{ steps.tagger.outputs.VERSION_TAG }}
